### ISSUE TITLE
System packages needed for numpy/scipy installation not present.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#120]
System packages needed to permit the installation of ``scipy`` Python package are not present. It appears ``numpy`` may install, but without certain features then required by ``scipy``.

Don't know at this point know what the missing packages are. Logging issue just so it is known.

```
Running setup.py install for scipy
lapack_opt_info:
openblas_lapack_info:
libraries openblas not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
NOT AVAILABLE

lapack_mkl_info:
mkl_info:
libraries mkl,vml,guide not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
NOT AVAILABLE

NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
libraries tatlas,tatlas not found in /opt/rh/rh-python34/root/usr/lib
libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries tatlas,tatlas not found in /usr/local/lib64
libraries lapack_atlas not found in /usr/local/lib64
libraries tatlas,tatlas not found in /usr/local/lib
libraries lapack_atlas not found in /usr/local/lib
libraries tatlas,tatlas not found in /usr/lib64/sse2
libraries lapack_atlas not found in /usr/lib64/sse2
libraries tatlas,tatlas not found in /usr/lib64
libraries lapack_atlas not found in /usr/lib64
libraries tatlas,tatlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries tatlas,tatlas not found in /usr/lib
libraries lapack_atlas not found in /usr/lib
libraries tatlas,tatlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries tatlas,tatlas not found in /usr/lib/
libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
NOT AVAILABLE

atlas_3_10_info:
libraries satlas,satlas not found in /opt/rh/rh-python34/root/usr/lib
libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries satlas,satlas not found in /usr/local/lib64
libraries lapack_atlas not found in /usr/local/lib64
libraries satlas,satlas not found in /usr/local/lib
libraries lapack_atlas not found in /usr/local/lib
libraries satlas,satlas not found in /usr/lib64/sse2
libraries lapack_atlas not found in /usr/lib64/sse2
libraries satlas,satlas not found in /usr/lib64
libraries lapack_atlas not found in /usr/lib64
libraries satlas,satlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries satlas,satlas not found in /usr/lib
libraries lapack_atlas not found in /usr/lib
libraries satlas,satlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries satlas,satlas not found in /usr/lib/
libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_3_10_info'>
NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
libraries ptf77blas,ptcblas,atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
libraries lapack_atlas not found in /usr/local/lib64
libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
libraries lapack_atlas not found in /usr/local/lib
libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
libraries lapack_atlas not found in /usr/lib64/sse2
libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
libraries lapack_atlas not found in /usr/lib64
libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries ptf77blas,ptcblas,atlas not found in /usr/lib
libraries lapack_atlas not found in /usr/lib
libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_threads_info'>
NOT AVAILABLE

atlas_info:
libraries f77blas,cblas,atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib
libraries f77blas,cblas,atlas not found in /usr/local/lib64
libraries lapack_atlas not found in /usr/local/lib64
libraries f77blas,cblas,atlas not found in /usr/local/lib
libraries lapack_atlas not found in /usr/local/lib
libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
libraries lapack_atlas not found in /usr/lib64/sse2
libraries f77blas,cblas,atlas not found in /usr/lib64
libraries lapack_atlas not found in /usr/lib64
libraries f77blas,cblas,atlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries f77blas,cblas,atlas not found in /usr/lib
libraries lapack_atlas not found in /usr/lib
libraries f77blas,cblas,atlas not found in /usr/lib/sse2
libraries lapack_atlas not found in /usr/lib/sse2
libraries f77blas,cblas,atlas not found in /usr/lib/
libraries lapack_atlas not found in /usr/lib/
<class 'numpy.distutils.system_info.atlas_info'>
NOT AVAILABLE

lapack_info:
libraries lapack not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
NOT AVAILABLE

lapack_src_info:
NOT AVAILABLE

NOT AVAILABLE

/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1542: UserWarning:
Atlas (http://math-atlas.sourceforge.net/) libraries not found.
Directories to search for the libraries can be specified in the
numpy/distutils/site.cfg file (section [atlas]) or by setting
the ATLAS environment variable.
warnings.warn(AtlasNotFoundError.__doc__)
/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1553: UserWarning:
Lapack (http://www.netlib.org/lapack/) libraries not found.
Directories to search for the libraries can be specified in the
numpy/distutils/site.cfg file (section [lapack]) or by setting
the LAPACK environment variable.
warnings.warn(LapackNotFoundError.__doc__)
/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1556: UserWarning:
Lapack (http://www.netlib.org/lapack/) sources not found.
Directories to search for the sources can be specified in the
numpy/distutils/site.cfg file (section [lapack_src]) or by setting
the LAPACK_SRC environment variable.
warnings.warn(LapackSrcNotFoundError.__doc__)
Running from scipy source directory.
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 265, in <module>
setup_package()
File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 262, in setup_package
setup(**metadata)
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/core.py", line 135, in setup
config = configuration()
File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 182, in configuration
config.add_subpackage('scipy')
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
caller_level = 2)
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
caller_level = caller_level + 1)
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
config = setup_module.configuration(*args)
File "scipy/setup.py", line 15, in configuration
config.add_subpackage('linalg')
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
caller_level = 2)
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
caller_level = caller_level + 1)
File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
config = setup_module.configuration(*args)
File "scipy/linalg/setup.py", line 20, in configuration
raise NotFoundError('no lapack/blas resources found')
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
Complete output from command /opt/rh/rh-python34/root/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ovzzqhd8/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9fo3wjif-record/install-record.txt --single-version-externally-managed --compile --user:
lapack_opt_info:

openblas_lapack_info:

libraries openblas not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

NOT AVAILABLE



lapack_mkl_info:

mkl_info:

libraries mkl,vml,guide not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

NOT AVAILABLE



NOT AVAILABLE



atlas_3_10_threads_info:

Setting PTATLAS=ATLAS

libraries tatlas,tatlas not found in /opt/rh/rh-python34/root/usr/lib

libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries tatlas,tatlas not found in /usr/local/lib64

libraries lapack_atlas not found in /usr/local/lib64

libraries tatlas,tatlas not found in /usr/local/lib

libraries lapack_atlas not found in /usr/local/lib

libraries tatlas,tatlas not found in /usr/lib64/sse2

libraries lapack_atlas not found in /usr/lib64/sse2

libraries tatlas,tatlas not found in /usr/lib64

libraries lapack_atlas not found in /usr/lib64

libraries tatlas,tatlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries tatlas,tatlas not found in /usr/lib

libraries lapack_atlas not found in /usr/lib

libraries tatlas,tatlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries tatlas,tatlas not found in /usr/lib/

libraries lapack_atlas not found in /usr/lib/

<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

NOT AVAILABLE



atlas_3_10_info:

libraries satlas,satlas not found in /opt/rh/rh-python34/root/usr/lib

libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries satlas,satlas not found in /usr/local/lib64

libraries lapack_atlas not found in /usr/local/lib64

libraries satlas,satlas not found in /usr/local/lib

libraries lapack_atlas not found in /usr/local/lib

libraries satlas,satlas not found in /usr/lib64/sse2

libraries lapack_atlas not found in /usr/lib64/sse2

libraries satlas,satlas not found in /usr/lib64

libraries lapack_atlas not found in /usr/lib64

libraries satlas,satlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries satlas,satlas not found in /usr/lib

libraries lapack_atlas not found in /usr/lib

libraries satlas,satlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries satlas,satlas not found in /usr/lib/

libraries lapack_atlas not found in /usr/lib/

<class 'numpy.distutils.system_info.atlas_3_10_info'>

NOT AVAILABLE



atlas_threads_info:

Setting PTATLAS=ATLAS

libraries ptf77blas,ptcblas,atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64

libraries lapack_atlas not found in /usr/local/lib64

libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib

libraries lapack_atlas not found in /usr/local/lib

libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2

libraries lapack_atlas not found in /usr/lib64/sse2

libraries ptf77blas,ptcblas,atlas not found in /usr/lib64

libraries lapack_atlas not found in /usr/lib64

libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries ptf77blas,ptcblas,atlas not found in /usr/lib

libraries lapack_atlas not found in /usr/lib

libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries ptf77blas,ptcblas,atlas not found in /usr/lib/

libraries lapack_atlas not found in /usr/lib/

<class 'numpy.distutils.system_info.atlas_threads_info'>

NOT AVAILABLE



atlas_info:

libraries f77blas,cblas,atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries lapack_atlas not found in /opt/rh/rh-python34/root/usr/lib

libraries f77blas,cblas,atlas not found in /usr/local/lib64

libraries lapack_atlas not found in /usr/local/lib64

libraries f77blas,cblas,atlas not found in /usr/local/lib

libraries lapack_atlas not found in /usr/local/lib

libraries f77blas,cblas,atlas not found in /usr/lib64/sse2

libraries lapack_atlas not found in /usr/lib64/sse2

libraries f77blas,cblas,atlas not found in /usr/lib64

libraries lapack_atlas not found in /usr/lib64

libraries f77blas,cblas,atlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries f77blas,cblas,atlas not found in /usr/lib

libraries lapack_atlas not found in /usr/lib

libraries f77blas,cblas,atlas not found in /usr/lib/sse2

libraries lapack_atlas not found in /usr/lib/sse2

libraries f77blas,cblas,atlas not found in /usr/lib/

libraries lapack_atlas not found in /usr/lib/

<class 'numpy.distutils.system_info.atlas_info'>

NOT AVAILABLE



lapack_info:

libraries lapack not found in ['/opt/rh/rh-python34/root/usr/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

NOT AVAILABLE



lapack_src_info:

NOT AVAILABLE



NOT AVAILABLE



/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1542: UserWarning:

Atlas (http://math-atlas.sourceforge.net/) libraries not found.

Directories to search for the libraries can be specified in the

numpy/distutils/site.cfg file (section [atlas]) or by setting

the ATLAS environment variable.

warnings.warn(AtlasNotFoundError.__doc__)

/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1553: UserWarning:

Lapack (http://www.netlib.org/lapack/) libraries not found.

Directories to search for the libraries can be specified in the

numpy/distutils/site.cfg file (section [lapack]) or by setting

the LAPACK environment variable.

warnings.warn(LapackNotFoundError.__doc__)

/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/system_info.py:1556: UserWarning:

Lapack (http://www.netlib.org/lapack/) sources not found.

Directories to search for the sources can be specified in the

numpy/distutils/site.cfg file (section [lapack_src]) or by setting

the LAPACK_SRC environment variable.

warnings.warn(LapackSrcNotFoundError.__doc__)

Running from scipy source directory.

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 265, in <module>

setup_package()

File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 262, in setup_package

setup(**metadata)

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/core.py", line 135, in setup

config = configuration()

File "/tmp/pip-build-ovzzqhd8/scipy/setup.py", line 182, in configuration

config.add_subpackage('scipy')

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage

caller_level = 2)

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage

caller_level = caller_level + 1)

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py

config = setup_module.configuration(*args)

File "scipy/setup.py", line 15, in configuration

config.add_subpackage('linalg')

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage

caller_level = 2)

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage

caller_level = caller_level + 1)

File "/opt/app-root/src/.local/lib/python3.4/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py

config = setup_module.configuration(*args)

File "scipy/linalg/setup.py", line 20, in configuration

raise NotFoundError('no lapack/blas resources found')

numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
```

**Comment by NumCruncher** [comment]
I am facing similar issue.  Not sure what package is missing.

**Comment by pkubatrh** [comment]
The atlas-devel package is what seems to be missing to be able to build numpy properly for scipy

**Comment by hhorak** [comment]
Installing atlas-devel means 2.1 M bigger image, which seems still good enough deal to me. +1 for installing atlas-devel in python images.

**Comment by hhorak** [comment]
> Installing atlas-devel means 2.1 M bigger image, which seems still good enough deal to me. +1 for installing atlas-devel in python images.

Sorry, I made a mistake. It's actually 24 M with all the deps.. Which is not that superb anymore.

Shouldn't we rather just document how to do it and users would create own image instead? Sad thing is that we're not able to do it in s2i, because we need root for installing atlas-devel package.

@bparees: Or is there a way to perform actions as root during `s2i build ...`?

**Comment by bparees** [comment]
@hhorak no, it's not possible to perform root actions during s2i build, particularly on openshift (where sudo is restricted).

**Comment by bparees** [comment]
numpy is a pretty common dependency, isn't it?  perhaps it makes sense to do this if we intend to provide a generally useful python image.

**Comment by hhorak** [comment]
> numpy is a pretty common dependency, isn't it? perhaps it makes sense to do this if we intend to provide a generally useful python image.

Sounds correct actually, after filling my knowledge gaps, it indeed seems like numpy is very popular, so worth the 24MB.

**Comment by bparees** [comment]
let's do it.

**Comment by pkubatrh** [comment]
Just FTR: Numpy can be built even without the atlas-devel package but the lapack modules needed by Scipy will not be built (and as such the Scipy build will fail). So the usefulness of this change would rather depend on the usefulness of Scipy and projects that have similar dependencies.

**Comment by hhorak** [comment]
Thanks @pkubatrh, I think it does not change much. I think we can also add a scipy project as an example of an application that we `s2i build` in the test suite, so we keep this package install-able.

**Comment by hhorak** [comment]
@pkubatrh, would you mind turning this to a PR, pls?

**Comment by pkubatrh** [comment]
Looking at Scipy's dependencies more closely I noticed it also depends on a Fortran compiler (gcc-gfortran). This would make the additional size (together with atlas-devel) 40MB.

**Comment by pkubatrh** [comment]
@hhorak @bparees ^ is this ok?

**Comment by hhorak** [comment]
@pkubatrh I think 40MB is still worth doing it.

**Comment by bparees** [comment]
agree, it seems painful not to have it.

**Comment by pkubatrh** [comment]
This can be closed as the PR has been merged in.
