### ISSUE TITLE
Numpy test not compatible with Python 3.3

### ISSUE THREAD

**Issue by andrewklau** [sclorg/s2i-python-container#189]
Numpy doesn't seem to be compatible with python 3.3 so tests would fail:

```
Your branch is up-to-date with 'origin/master'.
---> Installing application source ...
---> Installing dependencies ...
Downloading/unpacking gunicorn (from -r requirements.txt (line 1))
Downloading/unpacking numpy (from -r requirements.txt (line 2))
Running setup.py (path:/opt/app-root/build/numpy/setup.py) egg_info for package numpy
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/opt/app-root/build/numpy/setup.py", line 34, in <module>
raise RuntimeError("Python version 2.7 or >= 3.4 required.")
RuntimeError: Python version 2.7 or >= 3.4 required.
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/opt/app-root/build/numpy/setup.py", line 34, in <module>
raise RuntimeError("Python version 2.7 or >= 3.4 required.")
RuntimeError: Python version 2.7 or >= 3.4 required.
```

**Comment by andrewklau** [comment]
Oh just realised 3.3 is deprecated. Closing then.
