### ISSUE TITLE
Image centos/python-36-centos suffers from getpwuid() issue

### ISSUE THREAD

**Issue by vpavlin** [sclorg/s2i-python-container#247]
The issue is described here: https://bugs.python.org/issue10496

I've hit it today while trying to avoid #246 

```
+ exec jupyterhub -f /opt/app-root/etc/jupyterhub_config.py
Traceback (most recent call last):
  File "/opt/app-root/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/app.py", line 118, in <module>
    class NewToken(Application):
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/app.py", line 134, in NewToken
    name = Unicode(getuser())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000930000'
```

**Comment by mcyprian** [comment]
@vpavlin can you please describe how your workflow looks like when rebuilding jupyterhub from python container?

**Comment by mcyprian** [comment]
#246 was closed is this still relevant @vpavlin?

**Comment by vpavlin** [comment]
Probably not, sorry, I forgot co close this
