### ISSUE TITLE
Fedora tests are failing.

### ISSUE THREAD

**Issue by phracek** [sclorg/s2i-python-container#552]
Fedora tests, on s2i-python-container, are failing for this reason:

```bash
 [FAILED] for 'pyuwsgi-pipenv-test-app' test_application (00:00:55)
 [FAILED] for 'pyuwsgi-pipenv-test-app' test_application_with_user (00:00:53)
 [FAILED] for 'pyuwsgi-pipenv-test-app' test_application_enable_init_wrapper (00:00:52)
```
and RHEL8 3.9-minimal tests are 
```bash
 [FAILED] for 'pin-pipenv-version-test-app' test_application (00:00:54)
 [FAILED] for 'pin-pipenv-version-test-app' test_application_with_user (00:00:54)
 [FAILED] for 'pin-pipenv-version-test-app' test_application_enable_init_wrapper (00:00:53)
```

The reason is for `pyuwsgi-pipenv-test-app` test_application:

```bash
[INFO] Building the pyuwsgi-pipenv-test-app application image ...[0m

Sending build context to Docker daemon   68.1kB


Step 1/10 : FROM quay.io/fedora/python3-310:0
 ---> 89fe84bc57c3
Step 2/10 : LABEL "io.openshift.s2i.build.image"="quay.io/fedora/python3-310:0"       "io.openshift.s2i.build.source-location"="file:///root/sclorg/s2i-python-container/3.10/test/pyuwsgi-pipenv-test-app"
 ---> Running in 90ae5ebe00ca
Removing intermediate container 90ae5ebe00ca
 ---> 34bbcb091e51
Step 3/10 : USER root
 ---> Running in 1b543f0fa872
Removing intermediate container 1b543f0fa872
 ---> a839586a8552
Step 4/10 : COPY upload/src/ /tmp/src
 ---> 43d37a41b3b9
Step 5/10 : RUN chown -R 1001:0 /tmp/src
 ---> Running in 4786c08b039c
Removing intermediate container 4786c08b039c
 ---> 49a183e46a31
Step 6/10 : ENV ENABLE_PIPENV=1
 ---> Running in a189c7089db0
Removing intermediate container a189c7089db0
 ---> 9ddac27edd3d
Step 7/10 : ENV PIN_PIPENV_VERSION=2018.11.26
 ---> Running in bac0141d4d0f
Removing intermediate container bac0141d4d0f
 ---> f06d1d5d6c3f
Step 8/10 : USER 1001
 ---> Running in f811ea0c5beb
Removing intermediate container f811ea0c5beb
 ---> 021435ec9495
Step 9/10 : RUN /usr/libexec/s2i/assemble
 ---> Running in e6b018d33e26
---> Installing application source ...
---> Installing pipenv packaging tool ...
Collecting pipenv==2018.11.26
  Downloading pipenv-2018.11.26-py3-none-any.whl (5.2 MB)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)
Collecting certifi
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting virtualenv
  Downloading virtualenv-20.16.5-py3-none-any.whl (8.8 MB)
Requirement already satisfied: setuptools>=36.2.1 in ./.local/venvs/pipenv/lib/python3.10/site-packages (from pipenv==2018.11.26) (59.6.0)
Requirement already satisfied: pip>=9.0.1 in ./.local/venvs/pipenv/lib/python3.10/site-packages (from pipenv==2018.11.26) (21.3.1)
Collecting distlib<1,>=0.3.5
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Installing collected packages: platformdirs, filelock, distlib, virtualenv-clone, virtualenv, certifi, pipenv
Successfully installed certifi-2022.9.24 distlib-0.3.6 filelock-3.8.0 pipenv-2018.11.26 platformdirs-2.5.2 virtualenv-20.16.5 virtualenv-clone-0.5.7
[91mWARNING: You are using pip version 21.3.1; however, version 22.3 is available.
You should consider upgrading via the '/opt/app-root/src/.local/venvs/pipenv/bin/python3.10 -m pip install --upgrade pip' command.
[0m---> Installing dependencies via pipenv ...
[91mCourtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
[0m[91mCreating a Pipfile for this project…
[0m[91mRequirements file provided! Importing into Pipfile…
[0m[91mTraceback (most recent call last):
[0m[91m  File "/opt/app-root/src/.local/venvs/pipenv/lib64/python3.10/site-packages/pipenv/core.py", line 1803, in do_install
[0m[91m    [0m[91mimport_requirements(r=project.path_to(requirements), dev=dev)[0m[91m
[0m[91m  File "/opt/app-root/src/.local/venvs/pipenv/lib64/python3.10/site-packages/pipenv/core.py", line 222, in import_requirements
[0m[91m    [0m[91mreqs = [f for f in parse_requirements(r, session=pip_requests)][0m[91m
TypeError[0m[91m: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

[0m[91mTraceback (most recent call last):
[0m[91m  File "/opt/app-root/src/.local/bin/pipenv", line 8, in <module>
[0m[91m    sys.exit(cli())
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
[0m[91m    [0m[91mreturn self.main(*args, **kwargs)
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 717, in main
[0m[91m    rv = self.invoke(ctx)[0m[91m
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
[0m[91m    [0m[91mreturn _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
[0m[91m    [0m[91mreturn ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
[0m[91m    return callback(*args, **kwargs)[0m[91m
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
[0m[91m    return ctx.invoke(f, obj, *args, **kwargs)
[0m[91m  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
[0m[91m    return callback(*args, **kwargs)[0m[91m
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)[0m[91m
  File "/opt/app-root/src/.local/venvs/pipenv/lib64/python3.10/site-packages/pipenv/cli/command.py", line 235, in install
[0m[91m    retcode = do_install(
  File "/opt/app-root/src/.local/venvs/pipenv/lib64/python3.10/site-packages/pipenv/core.py", line 1804, in do_install
[0m[91m    except (UnicodeDecodeError, PipError) as e:
TypeError: [0m[91mcatching classes that do not inherit from BaseException is not allowed
[0mThe command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 1
```

The RHEL8-3.9-minimal container failed on `micropipenv-requirements-test-app` test failed for this reason:

```bash
Building the micropipenv-requirements-test-app application image ...[0m

STEP 1: FROM ubi8/python-39-minimal:1
STEP 2: LABEL "io.openshift.s2i.build.image"="ubi8/python-39-minimal:1"       "io.openshift.s2i.build.source-location"="file:///tmp/sclorg/s2i-python-container/3.9-minimal/test/micropipenv-requirements-test-app"
4b7a6f2efbb1e909fb7c7319cd9579e8f5d5d89482c2efd3e990b330f9045a81
STEP 3: USER root
5802a7f6da6cd00d00c3f2fd37db939078e6ebb9f2cb84398ab39a476c1d103f
STEP 4: COPY upload/src/ /tmp/src
1d102b380bca1fac0fdbff1af9eff269c66da269cccadd646cef795f86b4f1fd
STEP 5: RUN chown -R 1001:0 /tmp/src
cfd89d3ee5b00f2f21c0f58d3fa03beab9b11915cbad935dda47cd741613cf24
STEP 6: ENV ENABLE_MICROPIPENV=true
74b38f933e017d7405fb09aafa950e3c849d8198c40725a9a52a394389de234d
STEP 7: ENV DISABLE_SETUP_PY_PROCESSING=true
6c9aed5ca666c98b070f61920be02a6187134cfe06c86197564a67a178da904b
STEP 8: RUN cd /etc/pki/ca-trust/source/anchors && update-ca-trust extract
6f69e4b07d771e7da05dbb9ff5e06e67951e517451cae0579caa9343373a0e96
STEP 9: USER 1001
bc655fa55b24a56d62558e184e7b834113937966d384c6c26916a17ede69a983
STEP 10: RUN /usr/libexec/s2i/assemble
---> Installing application source ...
---> Installing micropipenv packaging tool ...
Collecting micropipenv[toml]
  Downloading micropipenv-1.4.3-py3-none-any.whl (23 kB)
Requirement already satisfied, skipping upgrade: pip>=9 in ./.local/venvs/micropipenv/lib/python3.9/site-packages (from micropipenv[toml]) (20.2.4)
Collecting toml; python_version < "3.11" and extra == "toml"
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: toml, micropipenv
Successfully installed micropipenv-1.4.3 toml-0.10.2
WARNING: You are using pip version 20.2.4; however, version 22.3 is available.
You should consider upgrading via the '/opt/app-root/src/.local/venvs/micropipenv/bin/python3.9 -m pip install --upgrade pip' command.
---> Installing dependencies via micropipenv ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!		Provenance and integrity of installed packages cannot be checked!
!!!
!!!		The provided requirements.txt file is not fully locked as not all dependencies are
!!!		pinned to specific versions with digests of artifacts to be installed.
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Collecting mod_wsgi
  Downloading mod_wsgi-4.9.4.tar.gz (497 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/app-root/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sgbqnc2w/mod-wsgi_a4d83b355c2343eeb37dee7c642d91ca/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sgbqnc2w/mod-wsgi_a4d83b355c2343eeb37dee7c642d91ca/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wtgn_ta6
       cwd: /tmp/pip-install-sgbqnc2w/mod-wsgi_a4d83b355c2343eeb37dee7c642d91ca/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-sgbqnc2w/mod-wsgi_a4d83b355c2343eeb37dee7c642d91ca/setup.py", line 88, in <module>
      raise RuntimeError('The %r command appears not to be installed or '
  RuntimeError: The 'apxs' command appears not to be installed or is not executable. Please check the list of prerequisites in the documentation for this package and install any missing Apache httpd server packages.
  ----------------------------------------
```

**Comment by frenzymadness** [comment]
Both fixed in #553
